#!/usr/bin/env bash

# Vars
name=prometheus
pidfile="$PWD/$name.pid"
datadir="$PWD/data/$name"
configdir="$PWD/config/$name"

# Check not running
if [[ -f "$pidfile" ]]; then
    echo "Error: found pidfile \"$pidfile\", instance running somewhere else"
    exit 1
fi

# Data dir
mkdir -p "$datadir"

rkt --insecure-options=image \
    run \
    --port 9090-tcp:9090 \
    --interactive \
    --volume prometheus-data,kind=host,source="$datadir" \
    --volume prometheus-config,kind=host,source="$configdir" \
    --mount volume=prometheus-data,target=/prometheus-data \
    --mount volume=prometheus-config,target=/prometheus-config \
    --exec '/bin/prometheus --config.file=/prometheus-config/prometheus.yml' \
    docker://prom/prometheus &

# Save pid
echo "$!" > "$pidfile"
